Controllers/ProfileController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Diagnostics;
using System.Xml.Linq;
using ThomasianMemoir.Data;
using ThomasianMemoir.Extensions;
using ThomasianMemoir.Models;
using ThomasianMemoir.ViewModels;

namespace ThomasianMemoir.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ILogger<DashboardController> _logger;
        private readonly AppDbContext _dbContext;
        private readonly IWebHostEnvironment _environment;
        private DbSet<UserInfo> UserInfo;
        private DbSet<UserPost> UserPost;
        private DbSet<UserPostLikes> UserPostLikes;
        private DbSet<UserPostComments> UserPostComments;
        private DbSet<UserPostMedia> UserPostMedia;

        private readonly UserManager<User> _userManager;

        public ProfileController(ILogger<DashboardController> logger, AppDbContext dbContext, UserManager<User> userManager, IWebHostEnvironment environment)
        {
            _logger = logger;
            _dbContext = dbContext;
            _userManager = userManager;
            _environment = environment;
            UserInfo = _dbContext.UserInfo;
            UserPost = _dbContext.UserPost;
            UserPostLikes = _dbContext.UserPostLikes;
            UserPostComments = _dbContext.UserPostComments;
            UserPostMedia = _dbContext.UserPostMedia;
        }

        [HttpGet]
        public async Task<IActionResult> Profile()
        {
            try
            {
                var currentUser = await _userManager.GetUserAsync(User);
                if (currentUser == null)
                {
                    return NotFound();
                }

                var userProfile = _dbContext.UserInfo.FirstOrDefault(up => up.UserId.Equals(currentUser.Id));
                if (userProfile == null)
                {
                    return NotFound();
                }

                var postsWithDetails = _dbContext.UserPost
                    .Where(post => post.UserId == currentUser.Id)
                    .OrderByDescending(post => post.PostDate)
                    .Include(post => post.Likes)
                    .Include(post => post.Media)
                    .ToList()
                    .Select(post =>
                    {
                        return new PostWithDetails
                        {
                            Post = post,
                            PostId = post.PostId,
                            UserMedia = post.Media,
                            UserLikes = post.Likes,
                            Liked = HasUserLikedPost(currentUser.Id, post.PostId)
                        };
                    })
                    .ToList();

                var viewModel = new ProfileViewModel
                {
                    UserId = currentUser.Id,
                    Email = currentUser.Email,
                    Username = currentUser.UserName,
                    FirstName = userProfile.FirstName,
                    LastName = userProfile.LastName,
                    YearLevel = userProfile.YearLevel,
                    ProfileDescription = userProfile.ProfileDescription,
                    DefaultAvatar = userProfile.DefaultAvatar,
                    DefaultBanner = userProfile.DefaultBanner,
                    ProfilePic = userProfile.ProfilePic,
                    BannerPic = userProfile.BannerPic,
                    Posts = postsWithDetails
                };
                return View(viewModel);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", new ErrorViewModel { ErrorMessage = "An unexpected error occurred." });
            }
        }

        [HttpGet]
        public async Task<IActionResult> PublicProfile(string userId)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(userId);
                if (user == null)
                {
                    return RedirectToAction("Error");
                }

                var userProfile = _dbContext.UserInfo.FirstOrDefault(up => up.UserId.Equals(user.Id));
                if (userProfile == null)
                {
                    return NotFound();
                }

                var postsWithDetails = _dbContext.UserPost
                    .Where(post => post.UserId == userId)
                    .OrderByDescending(post => post.PostDate)
                    .Include(post => post.Likes)
                    .Include(post => post.Media)
                    .ToList()
                    .Select(post =>
                    {
                        return new PostWithDetails
                        {
                            Post = post,
                            PostId = post.PostId,
                            UserMedia = post.Media,
                            UserLikes = post.Likes,
                            Liked = HasUserLikedPost(userId, post.PostId)
                        };
                    })
                    .ToList();

                var viewModel = new ProfileViewModel
                {
                    UserId = userId,
                    Email = user.Email,
                    Username = user.UserName,
                    FirstName = userProfile.FirstName,
                    LastName = userProfile.LastName,
                    YearLevel = userProfile.YearLevel,
                    ProfileDescription = userProfile.ProfileDescription,
                    DefaultAvatar = userProfile.DefaultAvatar,
                    DefaultBanner = userProfile.DefaultBanner,
                    ProfilePic = userProfile.ProfilePic,
                    BannerPic = userProfile.BannerPic,
                    Posts = postsWithDetails
                };
                return View(viewModel);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", new ErrorViewModel { ErrorMessage = "Cannot find Profile." });
            }
        }
        
        private bool HasUserLikedPost(string userId, int postId)
        {
            return _dbContext.UserPostLikes
                .Any(like => like.PostId == postId && like.UserId.Equals(userId));
        }

        [HttpGet]
        public IActionResult EditProfile()
        {
            try
            {
                var currentUser = _userManager.GetUserAsync(User).Result;
                if (currentUser == null)
                {
                    return NotFound();
                }

                var userProfile = _dbContext.UserInfo.FirstOrDefault(up => up.UserId.Equals(currentUser.Id));
                if (userProfile == null)
                {
                    return NotFound();
                }

                var viewModel = new EditProfileCompositeViewModel
                {
                    PersonalInfo = new EditProfilePersonalInfoViewModel  {
                        FirstName = userProfile.FirstName,
                        LastName = userProfile.LastName,
                        Username = currentUser.UserName,
                        Email = currentUser.Email,
                        YearLevel = userProfile.YearLevel
                    },
                    Password = new EditProfilePasswordViewModel(),
                    ProfileDescription = new EditProfileDescriptionViewModel  {
                        ProfileDescription = userProfile.ProfileDescription
                    },
                    ProfilePic = new EditProfileProfilePicViewModel  {
                        DefaultAvatar = userProfile.DefaultAvatar,
                        ProfilePic = userProfile.ProfilePic
                    },
                    BannerPic = new EditProfileBannerPicViewModel  {
                        DefaultBanner = userProfile.DefaultBanner,
                        BannerPic = userProfile.BannerPic
                    }
                };
                return View(viewModel);
            }
            catch (Exception e)
            {
                return RedirectToAction("Error", new ErrorViewModel { ErrorMessage = "An error occurred while retrieving user information." });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("UpdatePersonalInfo")]
        public async Task<IActionResult> UpdatePersonalInfo(EditProfileCompositeViewModel model) {
            TempData["TempProfileDescription"] = model.ProfileDescription.ProfileDescription;
            var user = _userManager.GetUserAsync(User).Result;
            var info = _dbContext.UserInfo.FirstOrDefault(up => up.UserId.Equals(user.Id));
            TempData["TempProfilePic"] = info.ProfilePic;
            TempData["TempDefaultAvatar"] = info.DefaultAvatar;
            TempData["TempBannerPic"] = info.BannerPic;
            TempData["TempDefaultBanner"] = info.DefaultBanner;
            TempData["IsPostOperation"] = true;
            ModelState.Remove("Password.OldPassword");
            ModelState.Remove("Password.NewPassword");
            ModelState.Remove("Password.ConfirmNewPassword");
            ModelState.Remove("ProfileDescription.ProfileDescription");
            ModelState.Remove("ProfilePic.DefaultAvatar");
            ModelState.Remove("ProfilePic.ProfilePic");
            ModelState.Remove("ProfilePic.NewProfilePic");
            ModelState.Remove("BannerPic.DefaultBanner");
            ModelState.Remove("BannerPic.BannerPic");
            ModelState.Remove("BannerPic.NewBannerPic");

            if (ModelState.IsValid)
            {
                TempData.Remove("TempProfilePic");
                TempData.Remove("TempBannerPic");
                var currentUser = await _userManager.GetUserAsync(User);

Views/Shared/_EmptyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"]</title>
    <!--CSS-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="@ViewData["CSSFile"]" asp-append-version="true" />
    <link rel="stylesheet" href="~/ThomasianMemoir.styles.css" asp-append-version="true" />
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!--Fontawesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
    <!--Favicon-->
    <link rel="icon" href="~/img/Thomasian_Memoir_Logo.png" type="image/gif" sizes="16x16">
</head>
<body>
    <main role="main">
        @RenderBody()
    </main>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="@ViewData["JSFile"]" asp-append-version="true"></script>
    <script src="@ViewData["JSFile2"]" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"]</title>
    <!--CSS-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="@ViewData["CSSFile"]" asp-append-version="true" />
    <link rel="stylesheet" href="~/ThomasianMemoir.styles.css" asp-append-version="true" />
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!--Fontawesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
    <!--Favicon-->
    <link rel="icon" href="~/img/Thomasian_Memoir_Logo.png" type="image/gif" sizes="16x16">
</head>
<body>
    <!--Navbar-->
    <header>
        <nav class="navbar navbar-expand-lg navbar" id="menu-bar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/Logo_with_Name.png" alt="UST Logo" class="navImg">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="margin-right: 20px;">
                    <span class="fa-solid fa-bars menu-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link link1" asp-area="" asp-controller="Home" asp-action="Index">HOME</a></li>
                        <li class="nav-item"><a class="nav-link link2" asp-area="" asp-controller="Home" asp-action="Login">LOGIN</a></li>
                        <li class="nav-item"><a class="nav-link link3" asp-area="" asp-controller="Home" asp-action="Registration">REGISTRATION</a></li>
                        @* @if (User.Identity.IsAuthenticated){ } *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main">
        @RenderBody()
    </main>
    
    <!--Footer-->
    <footer class="footer mt-auto py-3" style="text-align:center; background-color:#272218;">
        <div class="footerContent" style="overflow-wrap: break-word;
word-wrap: break-word;">
            ITELEC1C Final Project "Thomasian Memoir" by Kevin Kyle C. Coraza, Steve C. De Vera, Miguel Carlo G. Fajardo, Ira Rayzel S. Ji, Arianne Ashley M. Manaog
            <hr style="margin:0.3rem;">
            University of Santo Tomas A.Y. 2023-2024 &bull; ITELEC1C 3ITE Group 8
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
    <script src="@ViewData["JSFile"]" asp-append-version="true"></script>
    <script src="@ViewData["JSFile2"]" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoggedInLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"]</title>
    <!--CSS-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="@ViewData["CSSFile"]" asp-append-version="true" />
    <link rel="stylesheet" href="~/ThomasianMemoir.styles.css" asp-append-version="true" />
    <!--Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lilita+One&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!--Fontawesome-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
    <!--Favicon-->
    <link rel="icon" href="~/img/Thomasian_Memoir_Logo.png" type="image/gif" sizes="16x16">
</head>
<body>
    <!--Navbar-->
    <header>
        <nav class="navbar navbar-expand-lg navbar" id="menu-bar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="Homepage">
                    <img src="~/img/Logo_with_Name.png" alt="UST Logo" class="navImg">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="margin-right: 20px;">
                    <span class="fa-solid fa-bars menu-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link link1" asp-area="" asp-controller="Dashboard" asp-action="Homepage">HOME</a></li>
                        <li class="nav-item"><a class="nav-link link2" asp-area="" asp-controller="Profile" asp-action="Profile">PROFILE</a></li>
                        <li class="nav-item"><a class="nav-link link3" asp-area="" asp-controller="Home" asp-action="Logout">LOGOUT</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" style="min-height:100vh;">
        @RenderBody()
    </main>

    <!--Footer-->
    <footer class="footer mt-auto py-3" style="text-align:center; background-color:#272218;">
        <div class="footerContent">
            ITELEC1C Final Project "Thomasian Memoir" by Kevin Kyle C. Coraza, Steve C. De Vera, Miguel Carlo G. Fajardo, Ira Rayzel S. Ji, Arianne Ashley M. Manaog
            <hr style="margin:0.3rem;">
            University of Santo Tomas A.Y. 2023-2024 &bull; ITELEC1C 3ITE Group 8
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"></script>
    <script src="@ViewData["JSFile"]" asp-append-version="true"></script>
    <script src="@ViewData["JSFile2"]" asp-append-version="true"></script>
    <script src="@ViewData["JSFile3"]" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>