ViewModels/PostViewModel.cs
namespace ThomasianMemoir.ViewModels
{
    public class PostViewModel
    {
        public PostWithDetails PostWithDetails { get; set; }
        public string DefaultAvatar { get; set; }
        public string UserProfile { get; set; }
        public string UserId { get; internal set; }
    }
}

ViewModels/PostsViewModel.cs
 using ThomasianMemoir.Models;

namespace ThomasianMemoir.ViewModels
{
    public class PostsViewModel
    {
        //Retrieve Posts
        public List<PostWithDetails> PostsWithDetails { get; set; }
        public string DefaultAvatar { get; set; }
        public string UserProfile { get; set; }
        public string YearLevel { get; set; }
        //Create Post
        public string UserId { get; set; }
        public DateTime PostDate { get; set; }
        public string Content { get; set; }
        public int LikesCount { get; set; }
        public int CommentsCount { get; set; }
        public string PostType { get; set; }
        public bool IsSensitiveInfo { get; set; }
        public List<IFormFile>? PostMedia { get; set; }
    }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using ThomasianMemoir.Data;
using ThomasianMemoir.Models;
using ThomasianMemoir.ViewModels;
using ThomasianMemoir.Extensions;
using System;
using ThomasianMemoir.Services;

namespace ThomasianMemoir.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger<DashboardController> _logger;
        private readonly AppDbContext _dbContext;
        private readonly IWebHostEnvironment _environment;
        private readonly ProfanityFilterService profanityFilterService;
        private DbSet<UserInfo> Users;
        private DbSet<UserPost> UserPost;
        private DbSet<UserPostLikes> UserPostLikes;
        private DbSet<UserPostComments> UserPostComments;
        private DbSet<UserPostMedia> UserPostMedia;

        private readonly UserManager<User> _userManager;

        public DashboardController(ILogger<DashboardController> logger, AppDbContext dbContext, UserManager<User> userManager, IWebHostEnvironment environment)
        {
            _logger = logger;
            _dbContext = dbContext;
            _userManager = userManager;
            _environment = environment;
            profanityFilterService = new ProfanityFilterService();
            Users = _dbContext.UserInfo;
            UserPost = _dbContext.UserPost;
            UserPostLikes = _dbContext.UserPostLikes;
            UserPostComments = _dbContext.UserPostComments;
            UserPostMedia = _dbContext.UserPostMedia;
        }

        public IActionResult Homepage()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Freshmen()
        {
            var currentUser = _userManager.GetUserAsync(User).Result;
            var userProfile = _dbContext.UserInfo.FirstOrDefault(up => up.UserId.Equals(currentUser.Id));

            var freshmenPosts = _dbContext.UserPost
                .Where(post => post.PostType == "Freshmen")
                .OrderByDescending(post => post.PostDate)
                .Include(post => post.User)
                .Include(post => post.Likes)
                .Include(post => post.Comments)
                .Include(post => post.Media)
                .ToList()
                .Select(post =>
                {
                    var userInfo = _dbContext.UserInfo
                        .Where(u => u.UserId == post.UserId)
                        .FirstOrDefault();

                    return new PostWithDetails
                    {
                        Post = post,
                        UserId = post.UserId,
                        Username = _userManager.FindByIdAsync(post.UserId).Result.UserName,
                        UserMedia = post.Media,
                        UserLikes = post.Likes,
                        UserComments = post.Comments,
                        ProfilePic = userInfo?.ProfilePic,
                        DefaultAvatar = userInfo?.DefaultAvatar,
                        Liked = HasUserLikedPost(currentUser.Id, post.PostId)
                    };
                })
                .ToList();
            
            var viewModel = new PostsViewModel
            {
                PostsWithDetails = freshmenPosts.ToList(),
                UserProfile = userProfile?.ProfilePic,
                DefaultAvatar = userProfile?.DefaultAvatar,
                YearLevel = userProfile?.YearLevel
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Freshmen(PostsViewModel model)
        {
            ModelState.Remove("UserId");
            ModelState.Remove("PostType");
            ModelState.Remove("PostsWithDetails");
            ModelState.Remove("UserProfile");
            ModelState.Remove("DefaultAvatar");
            ModelState.Remove("YearLevel");
            if (ModelState.IsValid)
            {
                var allowedFileTypes = new List<string> { "image/jpe", "image/jpg", "image/jpeg", "image/gif", "image/png", "image/bmp", "image/ico", "image/svg", "image/tif", "image/tiff", "image/ai", "image/drw", "image/pct", "image/psp", "image/xcf", "image/psd", "image/raw", "image/webp", "video/avi", "video/divx", "video/flv", "video/m4v", "video/mkv", "video/mov", "video/mp4", "video/mpeg", "video/mpg", "video/ogm", "video/ogv", "video/ogx", "video/rm", "video/rmvb", "video/smil", "video/webm", "video/wmv", "video/xvid", "video/quicktime" };

                var currentUser = await _userManager.GetUserAsync(User);
                var userProfile = _dbContext.UserInfo.FirstOrDefault(up => up.UserId.Equals(currentUser.Id));

                if (currentUser != null)
                {
                    bool containsBadWords = profanityFilterService.ContainsBadWords(model.Content);

                    if (containsBadWords)
                    {
                        ModelState.AddModelError("postContent", "The post contains inappropriate language.");
                        return Json(new { success = false, error = "The post contains inappropriate language." });
                    }

                    var newPost = new UserPost
                    {
                        UserId = currentUser.Id,
                        User = userProfile,
                        PostDate = DateTime.Now,
                        Content = model.Content,
                        LikesCount = 0,
                        CommentsCount = 0,
                        PostType = "Freshmen",
                        IsSensitiveInfo = model.IsSensitiveInfo,
                        Media = new List<UserPostMedia>()
                    };

                    if (model.PostMedia != null)
                    {
                        for (int i = 0; i < model.PostMedia.Count; i++)
                        {
                            var file = model.PostMedia[i];

                            if (!allowedFileTypes.Contains(file.ContentType))
                            {
                                ModelState.AddModelError($"PostMedia[{i}]", "Invalid file type.");
                                return Json(new { success = false, error = "Invalid file type." });
                            }

                            var mediaType = GetMediaType(file.ContentType);

                            /*byte[] mediaBytes;
                            using (var memoryStream = new MemoryStream())
                            {
                                await file.CopyToAsync(memoryStream);
                                mediaBytes = memoryStream.ToArray();
                            }*/

                            var media = new UserPostMedia
                            {
                                MediaPath = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName),
                                MediaType = mediaType
                            };

                            var filePath = Path.Combine(_environment.WebRootPath, "uploads", media.MediaPath.TrimStart('/'));
                            using (var fileStream = new FileStream(filePath, FileMode.Create))
                            {
                                await file.CopyToAsync(fileStream);
                            }

                            newPost.Media.Add(media);
                        }
                    }

                    _dbContext.UserPost.Add(newPost);
                    await _dbContext.SaveChangesAsync();

                    return Json(new { success = true });
                }
            }
            return Json(new { success = false, error = "Invalid model state" });
        }

        [HttpGet]
        public IActionResult Sophomore()
        {
            var currentUser = _userManager.GetUserAsync(User).Result;
            var userProfile = _dbContext.UserInfo.FirstOrDefault(up => up.UserId.Equals(currentUser.Id));

            var freshmenPosts = _dbContext.UserPost
                .Where(post => post.PostType == "Sophomore")
                .OrderByDescending(post => post.PostDate)
                .Include(post => post.User)
                .Include(post => post.Likes)
                .Include(post => post.Comments)
                .Include(post => post.Media)
                .ToList()
                .Select(post =>
                {
                    var userInfo = _dbContext.UserInfo
                        .Where(u => u.UserId == post.UserId)
                        .FirstOrDefault();

                    return new PostWithDetails
                    {
                        Post = post,
                        UserId = post.UserId,
                        Username = _userManager.FindByIdAsync(post.UserId).Result.UserName,
                        UserMedia = post.Media,
                        UserLikes = post.Likes,
                        UserComments = post.Comments,
                        ProfilePic = userInfo?.ProfilePic,
                        DefaultAvatar = userInfo?.DefaultAvatar,
                        Liked = HasUserLikedPost(currentUser.Id, post.PostId)
                    };
                })
                .ToList();

            var viewModel = new PostsViewModel
            {
                PostsWithDetails = freshmenPosts.ToList(),
                UserProfile = userProfile?.ProfilePic,
                DefaultAvatar = userProfile?.DefaultAvatar,
                YearLevel = userProfile?.YearLevel
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Sophomore(PostsViewModel model)
        {
            ModelState.Remove("UserId");
            ModelState.Remove("PostType");
            ModelState.Remove("PostsWithDetails");
            ModelState.Remove("UserProfile");
            ModelState.Remove("DefaultAvatar");

Views/Dashboard/Homepage.cshtml
@{
    ViewData["Title"] = "Homepage";
    ViewData["CSSFile"] = "~/css/Homepage.css";
    ViewData["JSFile"] = "~/js/Dashboard.js";
}
<!--BANNER-->
<div class="banner">
    <img src="~/img/Covers/Cover-Home.png" alt="Homepage Cover">
</div>
<!--TITLE SECTION-->
<div class="row titleSection dashboard" id="dashboard" onclick="clickDashboard()">
    <a href="#dashboard" style="color:white; padding-bottom:0px;" id="linkDashboard">
        <div>
            DASHBOARDS
            <div class="fa-solid fa-chevron-down text-muted displayed" style="font-size:25px;" id="down-icon"></div>
        </div>
    </a>
</div>
<!--CARDS-->
<div class="container" style="margin-top:20px; margin-bottom:20px;">
    <div class="row justify-content-center">
        <!--FRESHMEN-->
        <div class="card col-md-5 m-3">
            <a asp-controller="Dashboard" asp-action="Freshmen" target="_self">
                <div class="cardFreshmenImg" style="background-position:bottom;">
                    <div class="hoverYellowBG">FRESHMEN</div>
                </div>
            </a>
        </div>
        <!--SOPHOMORE-->
        <div class="card col-md-5 m-3">
            <a asp-controller="Dashboard" asp-action="Sophomore" target="_self">
                <div class="cardSophomoreImg">
                    <div class="hoverBlackBG">SOPHOMORE</div>
                </div>
            </a>
        </div>
        <!--JUNIOR-->
        <div class="card col-md-5 m-3 btn">
            <a asp-controller="Dashboard" asp-action="Junior" target="_self">
                <div class="cardJuniorImg">
                    <div class="hoverBlueBG">JUNIOR</div>
                </div>
            </a>
        </div>
        <!--SENIOR-->
        <div class="card col-md-5 m-3">
            <a asp-controller="Dashboard" asp-action="Senior" target="_self">
                <div class="cardSeniorImg">
                    <div class="hoverWhiteBG">SENIOR</div>
                </div>
            </a>
        </div>
    </div>
</div>

Views/Dashboard/PostPictures.cshtml
@{
    Layout = "~/Views/Shared/_EmptyLayout.cshtml";
    ViewData["Title"] = "Post Pictures";
    ViewData["CSSFile"] = "~/css/PostPictures.css";
    ViewData["JSFile"] = "~/js/PostPictures.js";
    @model ThomasianMemoir.ViewModels.PostWithDetails;
    var postId = Model.PostId;
}
<div>
<div style="overflow:hidden; vertical-align:middle;">
    <div id="postCarousel" class="carousel" data-ride="carousel">
        <!--Index of image-->
        <div class="carousel-indicators" style="justify-content:center; top:20px;">
            <div class="num indicatorBG"></div>
        </div>
        <!--Images/Videos-->
        <div class="carousel-inner" style="display:flex; align-items:center;">
            <div class="blurredBG"></div>

            @foreach (var media in Model.UserMedia)
            {
            <div class="carousel-item @if(media == Model.UserMedia.First()) { <text>active</text> }">
                @{if (media.MediaPath != null && media.MediaPath.Length > 0)
                {                
                    if (media.MediaType == "Image")
                    {
                        <img src="@Url.Content("/uploads/" + media.MediaPath)" alt="Post Media">
                    }
                    else if (media.MediaType == "Video")
                    {
                    <video controls data-touch="false" class="embed-responsive vidContent" autoplay muted>
                        <source src="@Url.Content("/uploads/" + media.MediaPath)" alt="Post Media">
                        Your browser does not support the video tag.
                    </video>
                    }
                }
                }
            </div>
            } 
        </div>
        <!--Prev and next buttons-->
        <a class="carousel-control-prev" href="#postCarousel" role="button" data-slide="prev">
            <span class="fa-solid fa-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#postCarousel" role="button" data-slide="next">
                <span class="fa-solid fa-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
        <!--Back and exit buttons-->
        <div class="carousel-indicators" style="justify-content:end; top:20px;">
            <a asp-controller="Dashboard" asp-action="Post" asp-route-postId="@postId" class="fa-solid fa-xmark btn btnExit"></a>
        </div>
    </div>
</div>
</div>

Views/Dashboard/_CommentPartialView.cshtml
@model ThomasianMemoir.Models.UserPostComments

<div class="commentDiv" id="commentsSection">
    <div style="float:left; display:inline-block;">
        <a asp-controller="Profile" asp-action="PublicProfile" asp-route-userId="@Model.Commentator.UserId" style="pointer-events:auto;">
            <div class="profilePicComment">
                @if (Model.Commentator.ProfilePic != null)
                {
                    <img src="~/uploads/@Url.Content(Model.Commentator.ProfilePic)" style="clip-path:circle(50%);">
                }
                else
                {
                    <img src="~/img/Avatars/@Model.Commentator.DefaultAvatar" class="profileImage" style="clip-path:circle(50%);">
                }
            </div>
        </a>
    </div>
    <div style="display:block; text-align:start;">
      <span class="usernamePost btn" style="margin-left:70px; margin-bottom:5px; margin-right:10px;"><a asp-controller="Profile" asp-action="PublicProfile" asp-route-userId="@Model.UserId" style="display:inline-block; pointer-events:auto; position: relative;">@(Model.Commentator?.User?.UserName ?? "Unknown User")</a></span>
      <span class="timestamp">
        @{
            var timeDiff = DateTime.Now - Model.Timestamp;

            if (timeDiff.TotalSeconds < 60)
            {
                var seconds = (int)timeDiff.TotalSeconds;
                <text>Commented @seconds second@(seconds != 1 ? "s" : "") ago</text>
            }
            else if (timeDiff.TotalMinutes < 60)
            {
                var minutes = (int)timeDiff.TotalMinutes;
                <text>Commented @timeDiff.Minutes minute@(minutes != 1 ? "s" : "") ago</text>
            }
            else if (timeDiff.TotalHours < 24)
            {
                var hours = (int)timeDiff.TotalHours;
                <text>Commented @timeDiff.Hours hour@(hours != 1 ? "s" : "") ago</text>
            }
            else
            {
                <text>Commented on @Model.Timestamp.ToString("MM/dd/yyyy hh:mm tt")</text>
            }
        }
      </span>
    </div>
    <div class="comment">@Model.Comment</div>

    <!--Reply Button-->
    <button class="reply-button btn btnLink" style="margin-left:69px;" data-username="@(Model.Commentator?.User?.UserName ?? "Unknown User")" data-commentid="@Model.CommentId" data-parentcomment="@Model.Comment">Reply</button>

    <!--Replies-->
    <div class="replies-container reply" id="comment_@Model.CommentId">
    @foreach (var reply in Model.Replies)
    {
        @await Html.PartialAsync("_CommentPartialView", reply)
    }
    </div>
</div>